---
title: Seasoned Cook
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
  uploads:
    title: Uploads
    output: true
  workshops:
    title: Workshops
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
navigation:
- text: Home
  url: "/"
- text: About
  url: "/about/"
- text: Workshops
  url: "/workshops/"
- text: Recipes
  url: "/recipes/"
- text: Join
  url: "/join/"
permalink: pretty
